{{- if .Values.secretStore.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "myapp.fullname" . }}-secret-provider-class
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  provider: azure
  secretObjects:
    - secretName: myapp-secret-key
      type: Opaque
      data:
        - objectName: myapp-secret-key
          key: myapp-secret-key
    - secretName: myapp-other-secret-key
      type: Opaque
      data:
        - objectName: myapp-other-secret-key
          key: myapp-other-secret-key
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.secretStore.userAssignedIdentityID | quote }}
    keyvaultName: {{ .Values.secretStore.keyvaultName | quote }}
    cloudName: AzurePublicCloud
    objects: |
      array:
        - |
          objectName: myapp-secret-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: myapp-other-secret-key
          objectType: secret
          objectVersion: ""
    tenantId: {{ .Values.secretStore.tenantId | quote }}
{{- end }}