# Development environment values
environment: development
bgColor: white
fontColor: black
debug: "true"
logLevel: DEBUG
sdlc: development

image:
  tag: develop-latest

replicaCount: 1

gunicorn:
  workers: "1"
  reload: "true"

ingress:
  hosts:
    - host: myapp-development.azurelaboratory.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: myapp-tls
      hosts:
        - myapp-development.azurelaboratory.com

autoscaling:
  minReplicas: 1
  maxReplicas: 2

persistence:
  shareName: app-pages-dev