# Development environment values
# Standalone configuration (no layering needed)

environment: development
bgColor: white
fontColor: black
debug: "true"
logLevel: DEBUG
sdlc: development
image:
  tag: main
replicaCount: 1
gunicorn:
  workers: "1"
  reload: "true"
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-nonprod-dns"
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: myapp-development.azurelaboratory.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: myapp-tls
      hosts:
        - myapp-development.azurelaboratory.com
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
persistence:
  shareName: app-pages-dev
