# Production East US region-specific configuration
region: eastus

ingress:
  hosts:
    - host: myapp-prod-eastus.azurelaboratory.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: myapp-tls
      hosts:
        - myapp-prod-eastus.azurelaboratory.com

persistence:
  shareName: app-pages-prod-eastus