# Production West US3 region-specific configuration
region: westus3

ingress:
  hosts:
    - host: myapp-prod-westus3.azurelaboratory.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: myapp-tls
      hosts:
        - myapp-prod-westus3.azurelaboratory.com

persistence:
  shareName: app-pages-prod-westus3