# Staging environment base configuration
# Common settings for all staging regions

environment: staging
bgColor: grey
fontColor: white
debug: "false"
logLevel: INFO
sdlc: staging

image:
  tag: main-e000970

replicaCount: 1

gunicorn:
  workers: "2"
  threads: "4"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Base staging ingress configuration (will be overridden by region)
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod-dns"
    nginx.ingress.kubernetes.io/rewrite-target: /
  tls:
    - secretName: myapp-tls