apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

replicas:
- count: 1
  name: myapp

patches:
- path: patches/deployment-patch.yaml
- path: patches/secret-provider-patch.yaml
