apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodefront-production
  namespace: argocd
  labels:
    app: nodefront
    environment: production
    criticality: high
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rodmhgl/nodefront.git  # Update with your repository URL
    targetRevision: main
    path: kustomize/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: nodefront-prod
  syncPolicy:
    # Manual sync for production - remove comments to enable automated sync
    # automated:
    #   prune: true
    #   selfHeal: true
    #   allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 20  # Keep more history for production
  info:
    - name: 'Description'
      value: 'Flask application for displaying environment information - Production'
    - name: 'Owner'
      value: 'DevOps Team'
    - name: 'Environment'
      value: 'Production environment - Manual sync required'
    - name: 'SLA'
      value: '99.9% uptime'
