apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodefront-development
  namespace: argocd
  labels:
    app: nodefront
    environment: development
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rodstewart/nodefront.git  # Update with your repository URL
    targetRevision: main
    path: kustomize/overlays/development
  destination:
    server: https://kubernetes.default.svc
    namespace: nodefront-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  info:
    - name: 'Description'
      value: 'Flask application for displaying environment information - Development'
    - name: 'Owner'
      value: 'DevOps Team'
