apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: myapp-secret-provider-class
spec:
  parameters:
    userAssignedIdentityID: "0cc3d584-5d58-40e7-a9f8-f6f50c8d5adb"
    keyvaultName: "tfstate-rn"