kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: myapp-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns
spec:
  rules:
    - host: myapp.azurelaboratory.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: myapp-service
                port:
                  number: 3000
  tls:
    - secretName: myapp-tls
      hosts:
        - myapp.azurelaboratory.com
