apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodefront-helm-apps
  namespace: argocd
  labels:
    app: nodefront
    deployment-method: helm
    type: app-of-apps
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/nodefront.git
    targetRevision: main
    path: argocd-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3