apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app: nodefront
  name: nodefront
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: 'Namespace'
  - group: '*'
    kind: 'PersistentVolumeClaim'
  - group: '*'
    kind: 'PersistentVolume'
  - group: '*'
    kind: 'Pod'
  - group: '*'
    kind: 'SecretProviderClass'
  description: Node Frontend Flask Application Project
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
    name: 'in-cluster'
  - namespace: development-helm
    server: https://kubernetes.default.svc
    name: 'in-cluster'
  - namespace: staging-eastus-helm
    server: https://kubernetes.default.svc
    name: 'in-cluster'
  - namespace: staging-westus3-helm
    server: https://kubernetes.default.svc
    name: 'in-cluster'
  - namespace: production-eastus-helm
    server: https://kubernetes.default.svc
    name: 'in-cluster'
  - namespace: production-westus3-helm
    server: https://kubernetes.default.svc
    name: 'in-cluster'
  namespaceResourceWhitelist:
  - group: '*'
    kind: 'PersistentVolume'
  - group: '*'
    kind: 'Pod'
  - group: '*'
    kind: 'SecretProviderClass'
  - group: '*'
    kind: 'Service'
  - group: '*'
    kind: 'Deployment'
  - group: '*'
    kind: 'ConfigMap'
  - group: '*'
    kind: 'HorizontalPodAutoscaler'
  - group: '*'
    kind: 'Ingress'
  roles:
  - groups:
    - nodefront-admins
    name: admin
    policies:
    - p, proj:nodefront:admin, applications, *, nodefront/*, allow
    - p, proj:nodefront:admin, logs, get, nodefront/*, allow
    - p, proj:nodefront:admin, exec, create, nodefront/*, allow
  - groups:
    - nodefront-developers
    name: developer
    policies:
    - p, proj:nodefront:developer, applications, get, nodefront/*, allow
    - p, proj:nodefront:developer, applications, sync, nodefront/*, allow
    - p, proj:nodefront:developer, logs, get, nodefront/*, allow
  - groups:
    - nodefront-viewers
    name: viewer
    policies:
    - p, proj:nodefront:viewer, applications, get, nodefront/*, allow
  sourceRepos:
  - https://github.com/rodmhgl/nodefront.git