apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app: nodefront
  name: nodefront
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Node Frontend Flask Application Project
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/rodmhgl/nodefront.git