apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodefront-helm-production-eastus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app: nodefront
    deployment-method: helm
    environment: production
    region: eastus
spec:
  project: nodefront
  source:
    repoURL: https://github.com/rodmhgl/nodefront.git
    targetRevision: main
    path: helm/myapp
    helm:
      valueFiles:
        - values/production.yaml
        - values/production-eastus.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production-eastus-helm
  syncPolicy:
    automated:
      prune: false  # Manual sync for production safety
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 5