apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodefront-helm-staging-eastus
  namespace: argocd
  labels:
    app: nodefront
    deployment-method: helm
    environment: staging
    region: eastus
spec:
  project: default
  source:
    repoURL: https://github.com/rodmhgl/nodefront.git
    targetRevision: main
    path: helm/myapp
    helm:
      valueFiles:
        - values/staging.yaml
        - values/staging-eastus.yaml
      parameters:
        - name: image.tag
          value: v1.0.0
  destination:
    server: https://kubernetes.default.svc
    namespace: staging-eastus-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3