kind: SecretProviderClass
apiVersion: secrets-store.csi.x-k8s.io/v1
metadata:
  name: myapp-secret-provider-class
spec:
  provider: azure
  secretObjects:
    - secretName: myapp-secret-key
      type: Opaque
      data:
        - objectName: myapp-secret-key
          key: myapp-secret-key
    - secretName: myapp-other-secret-key
      type: Opaque
      data:
        - objectName: myapp-other-secret-key
          key: myapp-other-secret-key
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 0cc3d584-5d58-40e7-a9f8-f6f50c8d5adb
    keyvaultName: tfstate-rn
    cloudName: AzurePublicCloud
    objects: |
      array:
        - |
          objectName: myapp-secret-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: myapp-other-secret-key
          objectType: secret
          objectVersion: ""
    tenantId: d3164c0e-9807-4863-a439-becceb8459d9