apiVersion: v1
kind: PersistentVolume
metadata:
  name: myapp-page-files-pv
  labels:
    usage: myapp-storage-claim
spec:
  storageClassName: azurefile
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-pv-secret
    shareName: app-pages
    readOnly: false