name: cicd

on:
  push:
    paths:
      - src/**
      - Dockerfile
      - requirements.txt
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744


      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            rodstewart/nodefront
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix={{branch}}-,format=short
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

    outputs:
      docker_meta_version: ${{ steps.meta.outputs.version }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Update Kustomize image tag
        shell: bash
        run: |
          echo ${{ needs.ci.outputs.docker_meta_version }}
          cd kustomize/base
          sed -i 's|image: rodstewart/nodefront:.*|image: rodstewart/nodefront:${{ needs.ci.outputs.docker_meta_version }}|' deployment.yaml

      - name: Commit and push changes
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5
        with:
          message: 'Update image tag to ${{ needs.ci.outputs.docker_meta_version }}'

      - name: Install ArgoCD CLI
        shell: bash
        run: |
          curl -sSL -o argocd https://argocd.azurelaboratory.com/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd.azurelaboratory.com \
            --grpc-web \
            --username ${{ vars.ARGOCD_USERNAME }} \
            --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync nodefront